/**
 * Past Papers corpus — SERVER-ONLY access to the syllabai-pastpapers index.
 *
 * The corpus repo is ~4 GB of canonical PDFs we NEVER clone or vendor. The
 * committed index (src/data/pastpapers-index.json, generated by
 * scripts/build_pastpapers_index.ts from the git tree) holds the inventory:
 * which paper dirs exist per specification, and which materials (qp.pdf /
 * ms.pdf / er.pdf) each holds. PDFs themselves stream at runtime from
 * raw.githubusercontent.com (CORS-enabled) so the demo hosts nothing.
 *
 * This module imports the index JSON — import it ONLY from server
 * components; client components use @/lib/pastpapers-shared instead.
 *
 * Honesty rules (non-negotiable, demo discipline):
 *   - Corpus metadata is AI-IDENTIFIED (operator ratification pending) — the
 *     index is derived from the canonical layout, full manifests live in the
 *     corpus repo. Every surface says so.
 *   - Official exam durations are shown ONLY where attested in
 *     OFFICIAL_DURATIONS; anything else is an editable estimate labelled as
 *     such in the mock runner.
 *   - Interactive (Mode 2) papers exist ONLY where the parsed question corpus
 *     attests them (sourcePaper provenance, lib/past-papers.ts); everything
 *     else gets the honest "parsing roadmap" state, never a fake player.
 */
import indexJson from "@/data/pastpapers-index.json";
import {
  corpusRawPath,
  ialUnitTitle,
  sessionRankOf,
  specTitle,
  type CorpusIndexMeta,
  type CorpusPaper,
  type CorpusPaperEntry,
  type CorpusSession,
  type CorpusSpec,
} from "@/lib/pastpapers-shared";

// ── index (server-side) ────────────────────────────────────────────────────
interface CorpusIndex {
  meta: CorpusIndexMeta;
  specs: Record<string, CorpusSpec>;
}

export const corpusIndex = indexJson as unknown as CorpusIndex;
export {
  corpusRawUrl,
  corpusRawPath,
  sessionLabel,
  groupBySession,
  prettyBytes,
  specTitle,
} from "@/lib/pastpapers-shared";
export type { CorpusPaperEntry } from "@/lib/pastpapers-shared";

// ── course → corpus mapping ────────────────────────────────────────────────
/** Which corpus specs a demo course draws from, plus optional filters. */
interface CourseSpecMap {
  specs: string[];
  /** Retired specs surfaced in the SAME archive, badged "Legacy spec"
   *  (e.g. 4CH0 papers predate the 4CH1 course). Kept separate from
   *  `specs` so the current-spec mapping stays the primary identity. */
  legacySpecs?: string[];
  /** IAL maths 2018 lives in ONE spec folder — filter by unit code prefix. */
  units?: string[];
  /** 4MA1 tier filter: "F" (foundation) or "H" (higher). */
  tier?: "F" | "H";
  /** Per-science split of one corpus spec — 4SD0's three sciences share the
   *  spec folder (1B/1C/1P + R variants; the qualification has no Paper 2s),
   *  so each demo course filters to its own science's variants. Also used for
   *  the double-award courses' legacySpecs: 4SC0-era physics = 4PH0 1-series
   *  (the legacy Double Award comprised ONLY the three Paper 1s — spec Issue 3). */
  variants?: string[];
}

const IG = "pearson-edexcel/international-gcse";
const IA = "pearson-edexcel/international-a-level";

const COURSE_SPECS: Record<string, CourseSpecMap> = {
  "igcse-chemistry-19": {
    specs: [`${IG}/chemistry/4ch1`],
    // retired 4CH0 line (last sat Jan 2019) — same subject, shown badged
    legacySpecs: [`${IG}/chemistry/4ch0`],
  },
  "igcse-physics-19": {
    specs: [`${IG}/physics/4ph1`],
    // retired 4PH0 line (last sat Jan 2019) — same subject, shown badged
    legacySpecs: [`${IG}/physics/4ph0`],
  },
  "igcse-biology-19": {
    specs: [`${IG}/biology/4bi1`],
    // retired 4BI0 line (last sat Jan 2019) — same subject, shown badged
    legacySpecs: [`${IG}/biology/4bi0`],
  },
  "igcse-maths-a-18-foundation": { specs: [`${IG}/mathematics-a/4ma1`], tier: "F", legacySpecs: [`${IG}/mathematics-a/4ma0`] },
  "igcse-maths-a-18-higher": { specs: [`${IG}/mathematics-a/4ma1`], tier: "H", legacySpecs: [`${IG}/mathematics-a/4ma0`] },
  "igcse-maths-b-16": { specs: [`${IG}/mathematics-b/4mb1`], legacySpecs: [`${IG}/mathematics-b/4mb0`] },
  "igcse-further-maths-19": { specs: [`${IG}/further-pure-mathematics/4pm1`], legacySpecs: [`${IG}/further-pure-mathematics/4pm0`] },
  "igcse-accounting-17-financial-statements": { specs: [`${IG}/accounting/4ac1`] },
  "igcse-accounting-17-introduction-to-bookkeeping-and-accounting": {
    specs: [`${IG}/accounting/4ac1`],
  },
  "igcse-business-19": { specs: [`${IG}/business/4bs1`] },
  "igcse-economics-17": { specs: [`${IG}/economics/4ec1`], legacySpecs: [`${IG}/economics/4ec0`] },
  "igcse-ict-17": { specs: [`${IG}/ict/4it1`], legacySpecs: [`${IG}/ict/4it0`] },
  "igcse-english-language-a-16-paper-1-non-fiction-texts-and-transactional-writing": {
    specs: [`${IG}/english-language-a/4ea1`],
  },
  "igcse-english-language-a-16-paper-2-poetry-and-prose-texts-and-imaginative-writing": {
    specs: [`${IG}/english-language-a/4ea1`],
  },
  "igcse-english-language-a-16-paper-3-coursework": { specs: [`${IG}/english-language-a/4ea1`] },
  "igcse-english-literature-16": { specs: [`${IG}/english-literature/4et1`] },
  "igcse-geography-19": { specs: [`${IG}/geography/4ge1`] },
  // Science Double Award 4SD0: one corpus spec, split per science by variant.
  // The qualification assesses via Paper 1B/1C/1P (+ timezone R) only — it has
  // no Paper 2s, so the variant lists are intentionally 1-series only.
  //
  // Legacy (4SC0) era, same principle one generation earlier: the Double Award
  // comprised ONLY the three Paper 1s (4SC0/1B/1C/1P, 2h each — spec Issue 3),
  // and those papers ARE the single sciences' Paper 1s (4BI0/4CH0/4PH0) — the
  // covers print both codes (e.g. "4PH0/1PR" + "4SC0/1PR"), Pearson's own DAM
  // catalogs the 4xx0 papers under the Science (Double Award) subject, and the
  // only 4SC0_-named assets are three June-2011 mark schemes. So the legacy
  // archive for this course is the 4ph0 spec's 1-series, badged "Legacy spec";
  // a 4sc0 spec folder would be fabrication (no such question papers exist).
  // 2-series 4PH0 papers (single-award extension) surface via igcse-physics-19.
  "igcse-science-double-award-17-biology": {
    specs: [`${IG}/science-double-award/4sd0`],
    variants: ["1B", "1BR"],
  },
  "igcse-science-double-award-17-chemistry": {
    specs: [`${IG}/science-double-award/4sd0`],
    variants: ["1C", "1CR"],
  },
  "igcse-science-double-award-17-physics": {
    specs: [`${IG}/science-double-award/4sd0`],
    // retired 4SC0 line: its Physics Paper 1 = 4PH0 Paper 1 (1P/1PR, 2011-2019)
    legacySpecs: [`${IG}/physics/4ph0`],
    variants: ["1P", "1PR"],
  },
  "ial-chemistry-17": {
    specs: [`${IA}/chemistry/wch11`, `${IA}/chemistry/wch12`, `${IA}/chemistry/wch13`, `${IA}/chemistry/wch14`, `${IA}/chemistry/wch15`, `${IA}/chemistry/wch16`],
    // retired 2008-spec units (WCH01–06, last sat Jan 2019)
    legacySpecs: [`${IA}/chemistry/wch01`, `${IA}/chemistry/wch02`, `${IA}/chemistry/wch03`, `${IA}/chemistry/wch04`, `${IA}/chemistry/wch05`, `${IA}/chemistry/wch06`],
  },
  "ial-physics-19": {
    specs: [`${IA}/physics/wph11`, `${IA}/physics/wph12`, `${IA}/physics/wph13`, `${IA}/physics/wph14`, `${IA}/physics/wph15`, `${IA}/physics/wph16`],
    // retired 2008-spec units (WPH01–06)
    legacySpecs: [`${IA}/physics/wph01`, `${IA}/physics/wph02`, `${IA}/physics/wph03`, `${IA}/physics/wph04`, `${IA}/physics/wph05`, `${IA}/physics/wph06`],
  },
  "ial-biology-18": {
    specs: [`${IA}/biology/wbi11`, `${IA}/biology/wbi12`, `${IA}/biology/wbi13`, `${IA}/biology/wbi14`, `${IA}/biology/wbi15`, `${IA}/biology/wbi16`],
    // retired 2008-spec units (WBI01–06)
    legacySpecs: [`${IA}/biology/wbi01`, `${IA}/biology/wbi02`, `${IA}/biology/wbi03`, `${IA}/biology/wbi04`, `${IA}/biology/wbi05`, `${IA}/biology/wbi06`],
  },
  "ial-maths-20-pure-1": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WMA11"] },
  "ial-maths-20-pure-2": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WMA12"] },
  "ial-maths-20-pure-3": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WMA13"] },
  "ial-maths-20-pure-4": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WMA14"] },
  "ial-maths-20-mechanics-1": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WME01"] },
  "ial-maths-20-mechanics-2": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WME02"] },
  "ial-maths-20-statistics-1": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WST01"] },
  "ial-maths-20-statistics-2": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WST02"] },
  "ial-maths-20-decision-1": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WDM11"] },
  "ial-further-maths-18-further-pure-1": {
    specs: [`${IA}/mathematics/mathematics-2018`],
    units: ["WFM01"],
  },
};

export function corpusSpecsForCourse(slug: string): CourseSpecMap | null {
  return COURSE_SPECS[slug] ?? null;
}

// ── official exam durations (attested) ─────────────────────────────────────
/**
 * Official exam durations (minutes) — ATTESTED Edexcel timings only.
 * Keyed by full IGCSE reference ("4CH1/1C") or IAL unit code ("WCH11").
 * Everything not listed = null → the mock runner shows an editable estimate.
 */
const OFFICIAL_DURATIONS: Record<string, number> = {
  // IGCSE Sciences (2017 linear): Paper 1 = 2h, Paper 2 = 1h10 (Chem) / 1h15 (Phy/Bio)
  "4CH1/1C": 120, "4CH1/1CR": 120, "4CH1/2C": 70, "4CH1/2CR": 70,
  // Legacy IGCSE Chemistry 4CH0 (last sat Jan 2019; official 4CH0 spec:
  // Paper 1 = 2 hours, Paper 2 = 1 hour — qualifications.pearson.com;
  // R variants are the same papers in a different timezone)
  "4CH0/1C": 120, "4CH0/1CR": 120, "4CH0/2C": 60, "4CH0/2CR": 60,
  "4PH1/1P": 120, "4PH1/1PR": 120, "4PH1/2P": 75, "4PH1/2PR": 75,
  "4BI1/1B": 120, "4BI1/1BR": 120, "4BI1/2B": 75, "4BI1/2BR": 75,
  // IGCSE Maths A: Higher 1H/2H = 2h, Foundation 1F/2F = 1h30
  "4MA1/1H": 120, "4MA1/2H": 120, "4MA1/1F": 90, "4MA1/2F": 90,
  "4MA1/1HR": 120, "4MA1/2HR": 120, "4MA1/1FR": 90, "4MA1/2FR": 90,
  // IGCSE Further Pure Maths: Papers 1 & 2 = 2h
  "4PM1/1": 120, "4PM1/2": 120,
  // IGCSE Maths B: papers = 2h
  "4MB1/1": 120, "4MB1/2": 120,
  // IGCSE Science Double Award 4SD0: Paper 1B/1C/1P = 2h each (attested on
  // the QP covers, 2019-2025 sessions); no Paper 2s exist in the qualification
  "4SD0/1B": 120, "4SD0/1BR": 120, "4SD0/1C": 120, "4SD0/1CR": 120,
  "4SD0/1P": 120, "4SD0/1PR": 120,
  // IAL 2018 sciences: units 1/2 = 1h30, unit 3 = 1h20, units 4/5 = 1h45 (Phy 1h35), unit 6 = 1h50
  WCH11: 90, WCH12: 90, WCH13: 80, WCH14: 105, WCH15: 105, WCH16: 110,
  WPH11: 90, WPH12: 90, WPH13: 80, WPH14: 95, WPH15: 95, WPH16: 110,
  WBI11: 90, WBI12: 90, WBI13: 80, WBI14: 105, WBI15: 105, WBI16: 110,
  // Legacy IGCSE Biology 4BI0 (official 4BI0 spec: Paper 1 = 2h, Paper 2 = 1h)
  "4BI0/1B": 120, "4BI0/1BR": 120, "4BI0/2B": 60, "4BI0/2BR": 60,
  // Legacy IGCSE Physics 4PH0 (official 4PH0 spec: Paper 1 = 2h, Paper 2 = 1h;
  // R durations attested on the 2013-2018 R-variant covers — 4SC0-wave 2026-09-28)
  "4PH0/1P": 120, "4PH0/2P": 60, "4PH0/1PR": 120, "4PH0/2PR": 60,
  // Legacy IGCSE Maths A 4MA0 (official spec: F papers 1h30, H papers 2h)
  "4MA0/1F": 90, "4MA0/2F": 90, "4MA0/3H": 120, "4MA0/4H": 120,
  "4MA0/1FR": 90, "4MA0/2FR": 90, "4MA0/3HR": 120, "4MA0/4HR": 120,
  // Legacy Maths B 4MB0 (official spec: each paper 2h30)
  "4MB0/01": 150, "4MB0/01R": 150, "4MB0/02": 150, "4MB0/02R": 150,
  // Legacy Further Pure Maths 4PM0 (official spec: each paper 2h)
  "4PM0/01": 120, "4PM0/02": 120,
  // Old IAL 2008-spec units 1 & 2 = 1h30 (Pearson SAMs); WBI03 = 1h30 (spec)
  // Units 3–6 (chem/phys) unattested → editable estimate like everything else
  WCH01: 90, WCH02: 90, WPH01: 90, WPH02: 90, WBI01: 90, WBI02: 90, WBI03: 90,
  // IAL 2018 maths modules: 1h30 each
  WMA11: 90, WMA12: 90, WMA13: 90, WMA14: 90,
  WME01: 90, WME02: 90, WME03: 90,
  WST01: 90, WST02: 90, WST03: 90,
  WDM11: 90,
  WFM01: 90, WFM02: 90, WFM03: 90,
  // zero-padded unit variants (dirs are "4MB1-01" style → ref "4MB1/01")
  "4MB1/01": 120, "4MB1/02": 120, "4PM1/01": 120, "4PM1/02": 120,
};

function officialDuration(ref: string): number | null {
  if (OFFICIAL_DURATIONS[ref] != null) return OFFICIAL_DURATIONS[ref];
  const unit = ref.split("/")[0];
  return OFFICIAL_DURATIONS[unit] ?? null;
}

// ── entry construction ─────────────────────────────────────────────────────
function buildEntry(
  specKey: string,
  spec: CorpusSpec,
  sessionId: string,
  p: CorpusPaper,
  legacy = false,
): CorpusPaperEntry | null {
  // split dir at the LAST dash: "4CH1-1C" → 4CH1 + 1C; "WMA11-01A" → WMA11 + 01A
  const cut = p.d.lastIndexOf("-");
  if (cut <= 0 || cut === p.d.length - 1) return null;
  const unit = p.d.slice(0, cut);
  const variant = p.d.slice(cut + 1);
  const ref = `${unit}/${variant}`;
  const isIGCSE = spec.qual === "international-gcse";

  let title: string;
  let variantChip: string | null = null;
  if (isIGCSE) {
    title = `Paper ${variant}`;
    // "1CR" → Timezone R (SME wording); "1C" → no chip
    const tz = variant.match(/^(\d+[A-Z])R$/);
    if (tz) {
      title = `Paper ${tz[1]}`;
      variantChip = "Timezone R";
    }
  } else {
    title = ialUnitTitle(unit);
    const v = variant.match(/^0\d([A-Z])$/);
    if (v) variantChip = `Variant ${v[1]}`;
  }

  return {
    specKey,
    specTitle: specTitle(spec),
    qual: spec.qual,
    sessionId,
    dir: p.d,
    unit,
    variant,
    ref,
    title,
    specBadge: legacy ? "Legacy spec" : null,
    variantChip,
    qpBytes: p.qp,
    msBytes: p.ms,
    erBytes: p.er,
    durationMin: officialDuration(ref),
    qpPath: p.qp != null ? corpusRawPath(specKey, sessionId, p.d, "qp.pdf") : "",
    msPath: p.ms != null ? corpusRawPath(specKey, sessionId, p.d, "ms.pdf") : "",
  };
}

/**
 * All corpus papers for a course, flattened. Sorted newest session first,
 * then by reference. Papers missing BOTH qp and ms are dropped (nothing to
 * view).
 */
export function corpusPapersForCourse(slug: string): CorpusPaperEntry[] {
  const map = COURSE_SPECS[slug];
  if (!map) return [];
  const out: CorpusPaperEntry[] = [];
  const legacySet = new Set(map.legacySpecs ?? []);
  for (const specKey of [...map.specs, ...(map.legacySpecs ?? [])]) {
    const spec = corpusIndex.specs[specKey];
    if (!spec) continue;
    const legacy = legacySet.has(specKey);
    for (const session of spec.sessions as CorpusSession[]) {
      for (const p of session.papers as CorpusPaper[]) {
        if (p.qp == null && p.ms == null) continue;
        const entry = buildEntry(specKey, spec, session.id, p, legacy);
        if (!entry) continue;
        if (map.units && !map.units.includes(entry.unit)) continue;
        if (map.variants && !map.variants.includes(entry.variant)) continue;
        if (map.tier) {
          // 4MA1 variants: 1F/2F (foundation), 1H/2H (higher), optional R suffix
          const isH = entry.variant.includes("H");
          const isF = entry.variant.includes("F");
          if (map.tier === "H" && !isH) continue;
          if (map.tier === "F" && !isF) continue;
        }
        out.push(entry);
      }
    }
  }
  return out.sort(
    (a, b) =>
      sessionRankOf(b.sessionId) - sessionRankOf(a.sessionId) ||
      a.ref.localeCompare(b.ref) ||
      a.dir.localeCompare(b.dir),
  );
}

/** True when the corpus holds at least one mapped paper for this course. */
export function courseHasCorpusPapers(slug: string): boolean {
  return corpusPapersForCourse(slug).length > 0;
}

export function findCorpusPaper(
  slug: string,
  sessionId: string,
  dir: string,
): CorpusPaperEntry | null {
  return corpusPapersForCourse(slug).find((p) => p.sessionId === sessionId && p.dir === dir) ?? null;
}
